### ISSUE TITLE
App shows ERR_UNKNOWN_URL_SCHEME while clicking on an icon in web view.

### ISSUE THREAD

**Issue by harshagarwal8** [selendroid/selendroid#992]
The screenshot for the problem can be found on the giveb link.

https://groups.google.com/forum/#!topic/selendroid/QccqaSVYLvg

**Comment by lukeis** [comment]
I believe this is fixed with some of my recent changes. Please try with 0.17.0 of selendroid

**Comment by harshagarwal8** [comment]
Yes, it is fixed.

**Comment by vicwomg** [comment]
I know this is marked as fixed, but I'm still seeing this issue on 0.17.0 for our app. Can we re-open it? Seems as though all custom protocols in URLs will throw this error. We use these custom urls to launch other webviews or activities.

Everything works fine in 0.15.0 though, so it does seem to be a regression of some sort. 

appv5://
appstage://
